services:
  nlang:
    image: ghcr.io/sidecloudgroup/nlang:latest
    ports:
      - "13792:80"
    volumes:
      - ./config.toml:/app/config.toml:ro
      - ./backend/data:/app/backend/data
    restart: unless-stopped

